# If true, the plugin will use an external database defined below.
# If false, it will reuse Mirth Connect's internal database connection.
useExternalDb=false

# options: derby, mysql, postgres, oracle, sqlserver
database = postgres

# examples:
#   Derby                       jdbc:derby:${dir.appdata}/mirthdb;create=true
#   PostgreSQL                  jdbc:postgresql://localhost:5432/mirthdb
#   MySQL                       jdbc:mysql://localhost:3306/mirthdb
#   Oracle                      jdbc:oracle:thin:@localhost:1521:DB
#   SQL Server/Sybase (jTDS)    jdbc:jtds:sqlserver://localhost:1433/mirthdb
#   Microsoft SQL Server        jdbc:sqlserver://localhost:1433;databaseName=mirthdb
#   If you are using the Microsoft SQL Server driver, please also specify database.driver below
database.url = jdbc:postgresql://localhost:5432/mirthdb

# If using a custom or non-default driver, specify it here.
# example:
# Microsoft SQL server: database.driver = com.microsoft.sqlserver.jdbc.SQLServerDriver
# (Note: the jTDS driver is used by default for sqlserver)
#database.driver =

# Maximum number of connections allowed for the main read/write connection pool
database.max-connections = 20

# database credentials
database.username =
database.password =

#On startup, Maximum number of retries to establish database connections in case of failure
database.connection.maxretry = 2
