<?xml version="1.0"?>
<project name="rulebuilder-plugin" basedir="." default="build">

	<!-- Load shared plugin properties -->
	<dirname property="plugin.dir" file="${ant.file.rulebuilder-plugin}"/>
	<property file="${plugin.dir}/../build.properties" />

	<!-- Local properties -->
	<property name="classes" value="${basedir}/classes" />
	<property name="src.plugin" value="${server.src}/com/mirth/connect/plugins/rulebuilder" />
	<property name="lib" value="${server.lib.extensions}/rulebuilder" />
	<property name="dist" value="${server.extensions}/rulebuilder" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="init">
		<mkdir dir="${classes}" />
		<mkdir dir="${dist}" />
	</target>

	<target name="compile" depends="init">
		<javac srcdir="${server.src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<include name="com/mirth/connect/plugins/rulebuilder/" />
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<!-- Copy plugin metadata XML files -->
		<copy todir="${dist}">
			<fileset dir="${src.plugin}">
				<include name="*.xml" />
			</fileset>
		</copy>

		<!-- Copy extension libraries -->
		<copy todir="${dist}/lib" failonerror="false" quiet="true">
			<fileset dir="${lib}" />
		</copy>

		<!-- Create shared jar -->
		<jar destfile="${dist}/rulebuilder-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/rulebuilder/RuleBuilderRule.class" />
			<include name="com/mirth/connect/plugins/rulebuilder/RuleBuilderRule$Condition.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/rulebuilder-${version}.zip" basedir="${server.extensions}" includes="rulebuilder/" />
	</target>

</project>
