<?xml version="1.0"?>
<project name="serverlog-plugin" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.serverlog-plugin}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="classes" value="${basedir}/classes" />
	<property name="dist" value="${server.extensions}/serverlog" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<jar destfile="${dist}/serverlog-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/serverlog/ServerLogItem.class" />
			<include name="com/mirth/connect/plugins/serverlog/ServerLogServletInterface.class" />
		</jar>
		<jar destfile="${dist}/serverlog-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/serverlog/**" />
			<exclude name="com/mirth/connect/plugins/serverlog/ServerLogItem.class" />
			<exclude name="com/mirth/connect/plugins/serverlog/ServerLogServletInterface.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/serverlog-${version}.zip" basedir="${server.extensions}" includes="serverlog/" />
	</target>

</project>
