<?xml version="1.0"?>
<project name="textviewer" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.textviewer}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/textviewer" />

	<target name="clean">
	</target>

	<target name="build">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/textviewer-${version}.zip" basedir="${server.extensions}" includes="textviewer/**/*" />
	</target>

</project>
