<?xml version="1.0"?>
<project name="datatype-edi" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.datatype-edi}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/datatype-edi" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<copy todir="${dist}" file="${src}/edi-to-xml-mapping.xml" />
		<copy todir="${classes}/com/mirth/connect/plugins/datatypes/edi/xml">
			<fileset dir="${src}/com/mirth/connect/plugins/datatypes/edi/xml" />
		</copy>
		<jar destfile="${dist}/datatype-edi-shared.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeServerPlugin.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeClientPlugin.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeCodeTemplatePlugin.class" />
		</jar>
		<jar destfile="${dist}/datatype-edi-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeServerPlugin.class" />
		</jar>
		<jar destfile="${dist}/datatype-edi-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeClientPlugin.class" />
			<include name="com/mirth/connect/plugins/datatypes/edi/EDIDataTypeCodeTemplatePlugin.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/datatype-edi-${version}.zip" basedir="${server.extensions}" includes="datatype-edi/**/*" />
	</target>

</project>
