# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

# Gradle Properties
# ant.import is not supported by configuration cache
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true

# Java Configuration
java.sourceCompatibility=17
java.targetCompatibility=17

# Build Configuration
build.encoding=UTF-8
