# Plugin name
plugin.name=message-trends

# Build output
build.dir=build
classes.dir=${build.dir}/classes
dist.dir=${build.dir}/dist
plugin.lib=libs

# Mirth dependency paths (relative to plugin location)
server.lib=../../server/lib
client.lib=../../client/lib

# Paths to compiled class files of Mirth modules (used for referencing in classpath)
server.classes.dir=../../server/classes
client.classes.dir=../../client/classes

# Resource directories (Maven-style)
server.resources.dir=server/src/main/resources

# Path to MC setup directory where final packaged extensions go
server.setup.extensions=../../server/setup/extensions
server.setup.conf=../../server/setup/conf
# Signing properties
keystore_property_file=keystore.properties
signjar_thread_count=4
