<?xml version="1.0"?>
<project name="file-connector" basedir="." default="build">

	<!-- Load shared plugin properties -->
	<dirname property="plugin.dir" file="${ant.file.file-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<!-- Local properties -->
	<property name="classes" value="${basedir}/classes" />
	<property name="src.connector" value="${server.src}/com/mirth/connect/connectors/file" />
	<property name="lib" value="${server.lib.extensions}/file" />
	<property name="dist" value="${server.extensions}/file" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="init">
		<mkdir dir="${classes}" />
		<mkdir dir="${dist}" />
	</target>

	<target name="compile" depends="init">
		<javac srcdir="${server.src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<include name="com/mirth/connect/connectors/file/" />
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<!-- Copy plugin metadata XML files -->
		<copy todir="${dist}">
			<fileset dir="${src.connector}">
				<include name="*.xml" />
			</fileset>
		</copy>

		<!-- Copy extension libraries -->
		<copy todir="${dist}/lib" failonerror="false" quiet="true">
			<fileset dir="${lib}" />
		</copy>

		<!-- Create shared jar (classes needed by client) -->
		<jar destfile="${dist}/file-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/file/SchemeProperties.class" />
			<include name="com/mirth/connect/connectors/file/FTPSchemeProperties.class" />
			<include name="com/mirth/connect/connectors/file/SmbDialectVersion.class" />
			<include name="com/mirth/connect/connectors/file/SmbSchemeProperties.class" />
			<include name="com/mirth/connect/connectors/file/SftpSchemeProperties.class" />
			<include name="com/mirth/connect/connectors/file/S3SchemeProperties.class" />
			<include name="com/mirth/connect/connectors/file/FileReceiverProperties.class" />
			<include name="com/mirth/connect/connectors/file/FileDispatcherProperties.class" />
			<include name="com/mirth/connect/connectors/file/FileScheme.class" />
			<include name="com/mirth/connect/connectors/file/FileAction.class" />
			<include name="com/mirth/connect/connectors/file/FileConnectorServletInterface.class" />
		</jar>

		<!-- Create server jar -->
		<jar destfile="${dist}/file-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/file/**" />
			<exclude name="com/mirth/connect/connectors/file/SchemeProperties.class" />
			<exclude name="com/mirth/connect/connectors/file/FTPSchemeProperties.class" />
            <!-- 
            These are duplicated in both jars for some reason
			<exclude name="com/mirth/connect/connectors/file/SmbDialectVersion.class" />
			<exclude name="com/mirth/connect/connectors/file/SmbSchemeProperties.class" />
            -->
			<exclude name="com/mirth/connect/connectors/file/SftpSchemeProperties.class" />
			<exclude name="com/mirth/connect/connectors/file/S3SchemeProperties.class" />
			<exclude name="com/mirth/connect/connectors/file/FileReceiverProperties.class" />
			<exclude name="com/mirth/connect/connectors/file/FileDispatcherProperties.class" />
			<exclude name="com/mirth/connect/connectors/file/FileScheme.class" />
			<exclude name="com/mirth/connect/connectors/file/FileAction.class" />
			<exclude name="com/mirth/connect/connectors/file/FileConnectorServletInterface.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/file-${version}.zip" basedir="${server.extensions}" includes="file/**/*" />
	</target>

</project>
