<?xml version="1.0"?>
<project name="vm-connector" basedir="." default="build">

	<!-- Load shared plugin properties -->
	<dirname property="plugin.dir" file="${ant.file.vm-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<!-- Local properties -->
	<property name="classes" value="${basedir}/classes" />
	<property name="src.connector" value="${server.src}/com/mirth/connect/connectors/vm" />
	<property name="lib" value="${server.lib.extensions}/vm" />
	<property name="dist" value="${server.extensions}/vm" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="init">
		<mkdir dir="${classes}" />
		<mkdir dir="${dist}" />
	</target>

	<target name="compile" depends="init">
		<javac srcdir="${server.src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<include name="com/mirth/connect/connectors/vm/" />
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<!-- Copy plugin metadata XML files -->
		<copy todir="${dist}">
			<fileset dir="${src.connector}">
				<include name="*.xml" />
			</fileset>
		</copy>

		<!-- Copy extension libraries -->
		<copy todir="${dist}/lib" failonerror="false" quiet="true">
			<fileset dir="${lib}" />
		</copy>

		<!-- Create shared jar (classes needed by client) -->
		<jar destfile="${dist}/vm-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/vm/VmReceiverProperties.class" />
			<include name="com/mirth/connect/connectors/vm/VmDispatcherProperties.class" />
		</jar>

		<!-- Create server jar -->
		<jar destfile="${dist}/vm-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/vm/" />
			<exclude name="com/mirth/connect/connectors/vm/VmReceiverProperties.class" />
			<exclude name="com/mirth/connect/connectors/vm/VmDispatcherProperties.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/vm-${version}.zip" basedir="${server.extensions}" includes="vm/" />
	</target>

</project>
