<?xml version="1.0"?>
<project name="vm-connector" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.vm-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="classes" value="${basedir}/classes" />
	<property name="dist" value="${server.extensions}/vm" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/source.xml" />
		<copy todir="${dist}" file="${src}/destination.xml" />
		<jar destfile="${dist}/vm-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/vm/VmReceiverProperties.class" />
			<include name="com/mirth/connect/connectors/vm/VmDispatcherProperties.class" />
		</jar>
		<jar destfile="${dist}/vm-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/vm/VmReceiver.class" />
			<include name="com/mirth/connect/connectors/vm/VmDispatcher.class" />
		</jar>
		<jar destfile="${dist}/vm-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/vm/ChannelReader*.class" />
			<include name="com/mirth/connect/connectors/vm/ChannelWriter*.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/vm-${version}.zip" basedir="${server.extensions}" includes="vm/" />
	</target>

</project>
