<?xml version="1.0"?>
<project name="http-plugins" basedir="." default="build">

	<!-- Build order: httpauth first (http and ws depend on it). -->

	<dirname property="http.plugins.dir" file="${ant.file.http-plugins}"/>

	<target name="clean">
		<ant antfile="${http.plugins.dir}/httpauth/build.xml" target="clean" inheritall="false" />
		<ant antfile="${http.plugins.dir}/http/build.xml" target="clean" inheritall="false" />
		<ant antfile="${http.plugins.dir}/ws/build.xml" target="clean" inheritall="false" />
	</target>

	<target name="build">
		<ant antfile="${http.plugins.dir}/httpauth/build.xml" target="build" inheritall="false" />
		<ant antfile="${http.plugins.dir}/http/build.xml" target="build" inheritall="false" />
		<ant antfile="${http.plugins.dir}/ws/build.xml" target="build" inheritall="false" />
	</target>

	<target name="create-zip">
		<ant antfile="${http.plugins.dir}/httpauth/build.xml" target="create-zip" inheritall="false" />
		<ant antfile="${http.plugins.dir}/http/build.xml" target="create-zip" inheritall="false" />
		<ant antfile="${http.plugins.dir}/ws/build.xml" target="create-zip" inheritall="false" />
	</target>

</project>
