<?xml version="1.0"?>
<project name="mirth-server" basedir="." default="help">

	<property name="keystore_property_file" value="keystore.properties" />
	<property name="manifest_thread_count" value="4" />
	<property name="signjar_thread_count" value="4" />
	<property name="jdk_src_path" value="" />

	<target name="help">
		<echo>Mirth Connect Build Help</echo>
	</target>

	<target name="init">
		<property file="build.properties" />

		<path id="classpath">
			<fileset dir="${lib}" includes="**/*.jar" />
		</path>
	</target>

	<target name="clean" depends="init">
		<delete dir="${logs}" />
		<mkdir dir="${logs}" />

		<delete dir="${classes}" />
		<delete dir="${setup}" />
		<delete dir="${dist}" />
		<delete dir="${build}" />
		<delete dir="${docs.javadocs}" />

		<!-- Clean external plugins -->
		<ant antfile="${basedir}/../plugins/build.xml" target="clean" inheritAll="false" />
	</target>

	<target name="compile" depends="clean, init, create-javadocs">
		<!-- compile the source -->
		<mkdir dir="${classes}" />

		<!-- compile core + server (excludes plugin implementations) -->
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false" sourcepath="">
			<classpath refid="classpath" />
			<!-- Q: Why do I need to filter by *.java -->
			<!-- A: No idea, but if a normal directory or ** is used, it skips BasicModeProvider.java -->
			<exclude name="com/mirth/connect/connectors/**/*.java" />
			<exclude name="com/mirth/connect/plugins/*/**/*.java" />
			<exclude name="com/mirth/connect/server/util/DICOMMessageUtil.java" />
			<exclude name="com/mirth/connect/server/userutil/DICOMUtil.java" />
			<exclude name="com/mirth/connect/model/converters/DICOMConverter.java" />
			<exclude name="com/mirth/connect/server/attachments/dicom/*.java" />
			<exclude name="org/dcm4che2/" />
			<exclude name="com/mirth/connect/server/userutil/HTTPUtil.java" />
			<exclude name="com/mirth/connect/server/userutil/DatabaseConnectionFactory.java" />
		</javac>

		<!-- create version.properties file -->
		<propertyfile file="version.properties">
			<entry key="mirth.version" value="${version}" />
			<entry key="mirth.date" type="date" value="today" pattern="MMMM d, yyyy" />
		</propertyfile>

		<!-- copy resource files to be placed in jars -->
		<copy todir="${classes}">
			<fileset file="version.properties" />
			<fileset file="mirth-client.jnlp" />
		</copy>
		<copy todir="${classes}/com/mirth/connect/util">
			<fileset dir="${src}/com/mirth/connect/util">
				<include name="*.js" />
				<include name="*.txt" />
			</fileset>
		</copy>
	</target>

	
	<target name="create-crypto" depends="compile">
		<jar destfile="${setup.server.lib}/${crypto.jar}" basedir="${classes}">
			<include name="com/mirth/commons/encryption/**" />
		</jar>
	</target>

	<target name="create-client-core" depends="compile, create-crypto">
		<jar destfile="${setup.server.lib}/${client-core.jar}" basedir="${classes}">
			<include name="com/mirth/connect/client/core/**" />
			<include name="com/mirth/connect/model/**" />
			<include name="com/mirth/connect/userutil/**" />
			<include name="com/mirth/connect/util/**" />
			<include name="com/mirth/connect/server/util/ResourceUtil.class" />
			<include name="com/mirth/connect/server/util/DebuggerUtil.class" />
			<include name="org/mozilla/**" />
			<include name="org/glassfish/jersey/**" />
			<include name="de/**" />
			<include name="net/lingala/zip4j/unzip/**" />

			<include name="version.properties" />

			<exclude name="com/mirth/connect/model/converters/DICOMConverter.class" />
		</jar>
	</target>

	<target name="create-connectors" depends="create-client-core">

		<!-- Build all external plugins -->
		<ant antfile="${basedir}/../plugins/build.xml" target="build" inheritAll="false" />

		<!-- set the version on all connectors -->
		<replace dir="${extensions}" token="@mirthversion" value="${version}">
			<include name="**/*.xml" />
		</replace>
	</target>

	<target name="create-plugins" depends="create-connectors">
		<!-- set the version on all plugins -->
		<replace dir="${extensions}" token="@mirthversion" value="${version}">
			<include name="**/*.xml" />
		</replace>
	</target>

	<target name="create-setup" depends="init">
		<echo>Sub-project files have been copied into setup</echo>

		<!-- create the setup directory -->
		<mkdir dir="${setup}" />
		<mkdir dir="${setup.conf}" />
		<mkdir dir="${setup.extensions}" />
		<mkdir dir="${setup.public_html}" />
		<mkdir dir="${setup.public_api_html}" />
		<mkdir dir="${setup.server.lib}" />
		<mkdir dir="${setup.client.lib}" />
		<mkdir dir="${setup.manager.lib}" />
		<mkdir dir="${setup.cli.lib}" />
		<mkdir dir="${setup.logs}" />
		<mkdir dir="${setup.docs}" />
		<mkdir dir="${setup.server.launcher.lib}" />

		<!-- copy lib -->
		<copy todir="${setup.server.lib}">
			<fileset dir="${lib}">
				<exclude name="ant/**" />
				<exclude name="extensions/**" />
			</fileset>
		</copy>

		<!-- copy conf files -->
		<copy todir="${setup.conf}">
			<fileset dir="${conf}" />
		</copy>

		<!-- copy public html files -->
		<copy todir="${setup.public_html}">
			<fileset dir="${public_html}">
				<exclude name="Thumbs.db" />
			</fileset>
		</copy>
		
		<replace dir="${setup.public_html}" token="@mirthversion" value="${version}">
			<include name="*.html" />
		</replace>
		
		<!-- copy Swagger UI files -->
		<copy todir="${setup.public_api_html}">
			<fileset dir="${public_api_html}">
				<exclude name="Thumbs.db" />
			</fileset>
		</copy>

		<!-- copy extensions files -->
		<copy todir="${setup.extensions}">
			<fileset dir="${extensions}" />
		</copy>

		<!-- copy docs files -->
		<copy todir="${setup.docs}">
			<fileset dir="${docs}" />
		</copy>

		<!-- copy basedir files -->
		<copy todir="${setup}">
			<fileset dir="${basedir_includes}" />
		</copy>

		<!-- make oieserver script executable on unix platforms -->
		<chmod file="${setup}/oieserver" perm="755"/>

		<!-- create the server jar -->
		<jar destfile="${setup.server.lib}/${server.jar}" basedir="${classes}">
			<include name="com/mirth/connect/server/**" />
			<include name="com/mirth/connect/model/**" />
			<include name="com/mirth/connect/util/**" />
			<include name="com/mirth/connect/plugins/*.class" />
			<include name="com/mirth/connect/connectors/*.class" />
			<include name="org/**" />
			<include name="net/sourceforge/jtds/ssl/**" />

			<include name="mirth-client.jnlp" />

			<exclude name="com/mirth/connect/server/launcher/**" />
			<exclude name="org/dcm4che2/**" />
			<exclude name="com/mirth/connect/model/converters/DICOMConverter.class" />
			<exclude name="com/mirth/connect/server/attachments/dicom/DICOMAttachmentHandler.class" />
			<exclude name="com/mirth/connect/server/attachments/dicom/DICOMAttachmentHandlerProvider.class" />
		</jar>

		<!-- create the dbconf jar -->
		<jar destfile="${setup.server.lib}/${dbconf.jar}" basedir="${dbconf}" />

		<!-- create the mirth-launcher jar -->
		<jar destfile="${setup}/${mirth-launcher.jar}" basedir="${classes}">
			<include name="com/mirth/connect/server/launcher/**" />
			<include name="com/mirth/connect/server/extprops/**" />

			<manifest>
				<attribute name="Main-Class" value="com.mirth.connect.server.launcher.MirthLauncher" />
				<attribute name="Class-Path" value="server-lib/commons/commons-io-2.13.0.jar server-lib/commons/commons-configuration2-2.8.0.jar server-lib/commons/commons-lang3-3.20.0.jar server-lib/commons/commons-logging-1.2.jar server-lib/commons/commons-beanutils-1.9.4.jar server-lib/commons/commons-text-1.15.0.jar server-lib/commons/commons-collections-3.2.2.jar conf/" />
			</manifest>
		</jar>
		
		<!-- create the userutil-sources jar -->
		<jar destfile="${setup.client.lib}/${userutil-sources.jar}" basedir="${src}">
			<include name="com/mirth/connect/userutil/**.java" />
			<include name="com/mirth/connect/server/userutil/**.java" />
			<exclude name="**/package-info.java" />
			<exclude name="com/mirth/connect/server/userutil/HTTPUtil.java" />
			<exclude name="com/mirth/connect/server/userutil/DatabaseConnectionFactory.java" />
			<exclude name="com/mirth/connect/server/userutil/DICOMUtil.java" />
		</jar>

		<!-- remove svn folders -->
		<delete>
			<fileset dir="${setup}" includes="**/.svn" />
		</delete>
		
		<taskdef resource="net/sf/antcontrib/antlib.xml" classpathref="classpath" />


		<if>
			<equals arg1="${disableSigning}" arg2="true" />

			<then>
				<echo message="Signing jars for Java Web Start is disabled" />
			</then>

			<else>
				<!-- modify jar manifests -->
				<!-- don't modify bcprov, since it already has the manifest changes and is signed by BC -->
				<echo message="[Thread Count: ${manifest_thread_count}] Modifying jar manifests to add Permissions: all-permissions; Codebase: *; Application-Name: Mirth Connect" />
				<for param="jarFile" parallel="true" threadCount="${manifest_thread_count}">
					<fileset dir="${setup.client.lib}" includes="**/*.jar" excludes="bcp*.jar,bcutil*.jar"/>
					<fileset dir="${setup.extensions}" includes="**/*.jar" />
					<sequential>
						<apply executable="jar">
							<arg value="umf" />
							<arg line="custom_manifest.mf" />
							<srcfile />
							<fileset file="@{jarFile}"/>
						</apply>
					</sequential>
				</for>

				<property file="${keystore_property_file}" />
				<property name="signingTsa" value="http://timestamp.digicert.com" />

				<echo message="[Thread Count: ${signjar_thread_count}] Signing jars for Java Web Start" />

				<if>
					<equals arg1="${cert}" arg2="ca" />

					<!-- Sign jars with valid CA certificate -->
					<then>
						<echo message="Signing with CA certificate" />

						<for param="jarFile" parallel="true" threadCount="${signjar_thread_count}">
							<fileset dir="${setup.client.lib}" includes="**/*.jar" />
							<fileset dir="${setup.extensions}" includes="**/*.jar" />
							<sequential>
								<retry retrycount="5" retrydelay="1000">
									<signjar
											jar="@{jarFile}"
											alias="${key.alias}"
											storepass="${key.storepass}"
											storetype="${key.storetype}"
											providerclass="${key.providerclass}"
											providerarg="${key.providerarg}"
											tsaurl="${signingTsa}"
									>
										<!-- http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7127374 -->
										<sysproperty key="jsse.enableSNIExtension" value="false" />
										<sysproperty key="https.protocols" value="TLSv1.2,TLSv1.1" />
									</signjar>
								</retry>
							</sequential>
						</for>
					</then>

					<!-- Sign jars with self-signed certificate -->
					<else>
						<echo message="Signing with self-signed certificate" />

						<for param="jarFile" parallel="true" threadCount="${signjar_thread_count}">
							<fileset dir="${setup.client.lib}" includes="**/*.jar" />
							<fileset dir="${setup.extensions}" includes="**/*.jar" />
							<sequential>
								<retry retrycount="5" retrydelay="1000">
									<signjar
											jar="@{jarFile}"
											alias="${key.alias}"
											keystore="${key.keystore}"
											storepass="${key.storepass}"
											keypass="${key.keypass}"
											storetype="${key.storetype}"
											tsaurl="${signingTsa}"
											digestalg="SHA-256"
									>
										<!-- http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7127374 -->
										<sysproperty key="jsse.enableSNIExtension" value="false" />
										<sysproperty key="https.protocols" value="TLSv1.2,TLSv1.1" />
									</signjar>
								</retry>
							</sequential>
						</for>
					</else>
				</if>
			</else>
		</if>
	</target>

	<target name="create-extension-zips" depends="create-setup">
		<delete dir="${dist.extensions}" />
		<mkdir dir="${dist.extensions}" />

		<ant antfile="${basedir}/../plugins/build.xml" target="create-extension-zips" inheritAll="false" />
	</target>

	<target name="create-dist" depends="create-extension-zips">
		<mkdir dir="${dist}" />
	</target>
	
	<target name="create-javadocs" depends="init">
		<mkdir dir="${docs.javadocs}" />
		
		<javadoc sourcepath="${src}:${jdk_src_path}" destdir="${docs.javadocs.userapi}" packagenames="com.mirth.connect.server.userutil,com.mirth.connect.userutil,com.mirth.connect.plugins.httpauth.userutil" link="https://docs.oracle.com/en/java/javase/17/docs/api/">
			<classpath refid="classpath" />
			<arg line="-html5"/>
			<arg line="--add-modules=java.sql.rowset"/>
			<arg line="--add-exports=java.sql.rowset/com.sun.rowset=ALL-UNNAMED"/>
		</javadoc>
	</target>

	<target name="create-derby-db" depends="compile">
		<!-- re-create the embedded database -->
		<delete dir="mirthdb" />
		<java classname="com.mirth.connect.server.tools.ScriptRunner" fork="true" dir="${basedir}" failonerror="true">
			<classpath>
				<pathelement location="${setup.server.lib}/${server.jar}" />
				<pathelement location="classes" />
				<pathelement location="${setup.conf}" />
				<fileset dir="${lib}">
					<include name="log4j/log4j-api-2.17.2.jar" />
					<include name="log4j/log4j-core-2.17.2.jar" />
					<include name="database/derby-10.10.2.0.jar" />
					<include name="database/derbytools-10.10.2.0.jar" />
					<include name="commons/commons-io-2.13.0.jar" />
				</fileset>
			</classpath>
			<arg value="dbconf/derby/derby-database.sql" />
		</java>
	</target>

	<target name="dev-launcher" depends="init" description="This runs Mirth using the setup launcher">
		<java classname="com.mirth.connect.server.launcher.MirthLauncher" fork="true" dir="${setup}" failonerror="true">
			<classpath>
				<pathelement location="${setup}/mirth-launcher.jar" />
			</classpath>
		</java>
	</target>

	<target name="dev-run" depends="init" description="This runs the mirth server using the Eclipse environment">
		<java classname="com.mirth.connect.server.Mirth" fork="true" dir="${basedir}" failonerror="true">
			<classpath>
				<pathelement location="bin" />
				<pathelement location="conf" />
				<pathelement location="build" />
				<fileset dir="${lib}">
					<include name="**/*.jar" />
					<include name="*.jar" />
				</fileset>
			</classpath>
		</java>
	</target>
	
	<target name="test-init" depends="init">
		<delete dir="${test_classes}" />
		
		<path id="testclasspath">
			<fileset dir="testlib" includes="**/*.jar" />
			<dirset dir="${classes}"/>
			<path refid="classpath" />
		</path>
	</target>
	
	<target name="test-compile" depends="test-init">
		<!-- compile the source -->
		<mkdir dir="${test_classes}" />
		
		<javac srcdir="${test}" destdir="${test_classes}" debug="on" includeAntRuntime="false">
			<classpath refid="testclasspath" />
			<compilerarg value="--add-modules=java.sql.rowset" />
			<compilerarg value="--add-exports=java.sql.rowset/com.sun.rowset=ALL-UNNAMED" />
			<compilerarg value="--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED" />
			<compilerarg value="--add-exports=java.base/sun.security.provider=ALL-UNNAMED" />
		</javac>
		
		<copy todir="${test_classes}">
			<fileset dir="${test}">
				<include name="**/*.xml" />
				<include name="**/*.json" />
			</fileset>
		</copy>
		
		<jar destfile="${test.dist}/${tests.jar}" basedir="${test_classes}">
			<include name="**/*" />
		</jar>
	</target>

	<path id="jacoco.classpath">
		<fileset dir="lib/ant">
			<include name="org.jacoco.ant-0.8.8.jar"/>
			<include name="org.jacoco.core-0.8.8.jar"/>
			<include name="org.jacoco.report-0.8.8.jar"/>
			<include name="org.jacoco.agent-0.8.8.jar"/>
			<include name="asm-9.2.jar"/>
			<include name="asm-tree-9.2.jar"/>
			<include name="asm-commons-9.2.jar"/>
		</fileset>
	</path>

	<taskdef uri="antlib:org.jacoco.ant"
			 resource="org/jacoco/ant/antlib.xml"
			 classpathref="jacoco.classpath"/>

	<target name="test-run" depends="test-compile">
		<property name="junit-reports" value="junit-reports" />
		<property name="junit-html" value="junit-html" />
		<property name="code-coverage-reports" value="code-coverage-reports" />
		<delete dir="${junit-reports}" />
		<delete dir="${code-coverage-reports}" />
		<delete dir="${junit-html}" />

		<mkdir dir="${junit-reports}" />
		<mkdir dir="${code-coverage-reports}" />
		<mkdir dir="${junit-html}" />

		<jacoco:coverage destfile="${code-coverage-reports}/jacoco.exec" xmlns:jacoco="antlib:org.jacoco.ant" exclclassloader="sun.reflect.DelegatingClassLoader:javassist.Loader" >
			<junit haltonfailure="false" fork="true" forkmode="once">
				<jvmarg value="-Xms128m" />
				<jvmarg value="-Xmx2048m" />
				<!-- https://stackoverflow.com/questions/54205486 -->
				<jvmarg value="-Xshare:off" />
				<jvmarg value="--add-exports=java.base/com.sun.crypto.provider=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.base/java.util=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.base/java.lang=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.base/java.lang.reflect=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.base/java.text=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.base/jdk.internal.misc=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.desktop/java.awt=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.desktop/java.awt.font=ALL-UNNAMED" />
				<jvmarg value="--add-opens=java.sql/java.sql=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.sql.rowset/com.sun.rowset=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.sql.rowset/com.sun.rowset.internal=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.sql.rowset/com.sun.rowset.providers=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.sql.rowset/javax.sql.rowset=ALL-UNNAMED"/>
				<jvmarg value="--add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED" />
				<classpath>
					<path refid="testclasspath" />
					<dirset dir="${test_classes}"/>
				</classpath>
				<formatter type="xml" />
				<batchtest todir="${junit-reports}">
					<fileset dir="${test_classes}">
						<include name="**/*Test.class" />
					</fileset>
				</batchtest>
			</junit>
		</jacoco:coverage>

		<!-- Generate HTML report from JUnit XML output -->
		<junitreport todir="${junit-reports}">
			<fileset dir="${junit-reports}">
				<include name="TEST-*.xml"/>
			</fileset>
			<report format="frames" todir="${junit-html}" />
		</junitreport>
	</target>
	
	<target name="remove-classes" depends="init">
		<!-- delete the compiled classes folder -->
		<delete dir="${classes}" />
		<delete dir="${test_classes}" />
	</target>
</project>
