<?xml version="1.0"?>
<project name="datatype-delimited" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.datatype-delimited}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/datatype-delimited" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<jar destfile="${dist}/datatype-delimited-shared.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeServerPlugin.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/delimited/DelimitedBatchAdaptor.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/delimited/DelimitedBatchReader.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeClientPlugin.class" />
			<exclude name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeCodeTemplatePlugin.class" />
		</jar>
		<jar destfile="${dist}/datatype-delimited-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeServerPlugin.class" />
			<include name="com/mirth/connect/plugins/datatypes/delimited/DelimitedBatchAdaptor.class" />
			<include name="com/mirth/connect/plugins/datatypes/delimited/DelimitedBatchReader.class" />
		</jar>
		<jar destfile="${dist}/datatype-delimited-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeClientPlugin.class" />
			<include name="com/mirth/connect/plugins/datatypes/delimited/DelimitedDataTypeCodeTemplatePlugin.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/datatype-delimited-${version}.zip" basedir="${server.extensions}" includes="datatype-delimited/**/*" />
	</target>

</project>
