<?xml version="1.0"?>
<project name="globalmapviewer-plugin" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.globalmapviewer-plugin}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="classes" value="${basedir}/classes" />
	<property name="dist" value="${server.extensions}/globalmapviewer" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<jar destfile="${dist}/globalmapviewer-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapServletInterface.class" />
		</jar>
		<jar destfile="${dist}/globalmapviewer-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/globalmapviewer/DefaultGlobalMapController.class" />
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapController.class" />
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapProvider.class" />
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapServlet.class" />
		</jar>
		<jar destfile="${dist}/globalmapviewer-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapClient*.class" />
			<include name="com/mirth/connect/plugins/globalmapviewer/GlobalMapPanel*.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/globalmapviewer-${version}.zip" basedir="${server.extensions}" includes="globalmapviewer/" />
	</target>

</project>
