<?xml version="1.0"?>
<project name="smtp-connector" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.smtp-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/smtp" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/destination.xml" />
		<jar destfile="${dist}/smtp-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/smtp/SmtpDispatcherProperties.class" />
			<include name="com/mirth/connect/connectors/smtp/SmtpConnectorServletInterface.class" />
			<include name="com/mirth/connect/connectors/smtp/Attachment.class" />
		</jar>
		<jar destfile="${dist}/smtp-server.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/connectors/smtp/SmtpDispatcherProperties.class" />
			<exclude name="com/mirth/connect/connectors/smtp/SmtpConnectorServletInterface.class" />
			<exclude name="com/mirth/connect/connectors/smtp/Attachment.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/smtp-${version}.zip" basedir="${server.extensions}" includes="smtp/**/*" />
	</target>

</project>
