<?xml version="1.0"?>
<project name="jdbc-connector" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.jdbc-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/jdbc" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/source.xml" />
		<copy todir="${dist}" file="${src}/destination.xml" />
		<jar destfile="${dist}/jdbc-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/jdbc/DatabaseReceiverProperties.class" />
			<include name="com/mirth/connect/connectors/jdbc/DatabaseDispatcherProperties.class" />
			<include name="com/mirth/connect/connectors/jdbc/DatabaseConnectionInfo.class" />
			<include name="com/mirth/connect/connectors/jdbc/Table.class" />
			<include name="com/mirth/connect/connectors/jdbc/Column.class" />
			<include name="com/mirth/connect/connectors/jdbc/DatabaseConnectorServletInterface.class" />
		</jar>
		<jar destfile="${dist}/jdbc-server.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/connectors/jdbc/DatabaseReceiverProperties.class" />
			<exclude name="com/mirth/connect/connectors/jdbc/DatabaseDispatcherProperties.class" />
			<exclude name="com/mirth/connect/connectors/jdbc/DatabaseConnectionInfo.class" />
			<exclude name="com/mirth/connect/connectors/jdbc/Table.class" />
			<exclude name="com/mirth/connect/connectors/jdbc/Column.class" />
			<exclude name="com/mirth/connect/connectors/jdbc/DatabaseConnectorServletInterface.class" />
		</jar>
		<mkdir dir="${dist}/src" />
		<jar destfile="${dist}/src/jdbc-userutil-sources.jar" basedir="${src}">
			<include name="com/mirth/connect/server/userutil/DatabaseConnectionFactory.java" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/jdbc-${version}.zip" basedir="${server.extensions}" includes="jdbc/**/*" />
	</target>

</project>
