<?xml version="1.0"?>
<project name="jms-connector" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.jms-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/jms" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/source.xml" />
		<copy todir="${dist}" file="${src}/destination.xml" />
		<jar destfile="${dist}/jms-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/jms/JmsConnectorProperties.class" />
			<include name="com/mirth/connect/connectors/jms/JmsReceiverProperties.class" />
			<include name="com/mirth/connect/connectors/jms/JmsDispatcherProperties.class" />
			<include name="com/mirth/connect/connectors/jms/JmsConnectorServletInterface.class" />
		</jar>
		<jar destfile="${dist}/jms-server.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/connectors/jms/JmsConnectorProperties.class" />
			<exclude name="com/mirth/connect/connectors/jms/JmsReceiverProperties.class" />
			<exclude name="com/mirth/connect/connectors/jms/JmsDispatcherProperties.class" />
			<exclude name="com/mirth/connect/connectors/jms/JmsConnectorServletInterface.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/jms-${version}.zip" basedir="${server.extensions}" includes="jms/" />
	</target>

</project>
