<?xml version="1.0"?>
<project name="datatype-raw" basedir="." default="build">

	<!-- Load shared plugin properties -->
	<dirname property="plugin.dir" file="${ant.file.datatype-raw}"/>
	<property file="${plugin.dir}/../build.properties" />

	<!-- Local properties -->
	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="dist" value="${server.extensions}/datatype-raw" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<jar destfile="${dist}/datatype-raw-shared.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/plugins/datatypes/raw/RawDataTypeServerPlugin.class" />
		</jar>
		<jar destfile="${dist}/datatype-raw-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/datatypes/raw/RawDataTypeServerPlugin.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/datatype-raw-${version}.zip" basedir="${server.extensions}" includes="datatype-raw/**/*" />
	</target>

</project>
