<?xml version="1.0"?>
<project name="dicom-plugins" basedir="." default="build">

	<!-- Build order: connector-dicom first (datatype-dicom and dicomviewer depend on it). -->

	<dirname property="dicom.plugins.dir" file="${ant.file.dicom-plugins}"/>

	<target name="clean">
		<ant antfile="${dicom.plugins.dir}/connector-dicom/build.xml" target="clean" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/datatype-dicom/build.xml" target="clean" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/dicomviewer/build.xml" target="clean" inheritall="false" />
	</target>

	<target name="build">
		<ant antfile="${dicom.plugins.dir}/connector-dicom/build.xml" target="build" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/datatype-dicom/build.xml" target="build" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/dicomviewer/build.xml" target="build" inheritall="false" />
	</target>

	<target name="create-zip">
		<ant antfile="${dicom.plugins.dir}/connector-dicom/build.xml" target="create-zip" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/datatype-dicom/build.xml" target="create-zip" inheritall="false" />
		<ant antfile="${dicom.plugins.dir}/dicomviewer/build.xml" target="create-zip" inheritall="false" />
	</target>

</project>
