<?xml version="1.0"?>
<project name="directoryresource-plugin" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.directoryresource-plugin}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="classes" value="${basedir}/classes" />
	<property name="dist" value="${server.extensions}/directoryresource" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<jar destfile="${dist}/directoryresource-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourceProperties.class" />
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourceServletInterface.class" />
		</jar>
		<jar destfile="${dist}/directoryresource-server.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourcePlugin.class" />
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourceServlet.class" />
		</jar>
		<jar destfile="${dist}/directoryresource-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourceClientPlugin.class" />
			<include name="com/mirth/connect/plugins/directoryresource/DirectoryResourcePropertiesPanel*.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/directoryresource-${version}.zip" basedir="${server.extensions}" includes="directoryresource/" />
	</target>

</project>
