<project name="webadmin" basedir="." default="dist">
	<!-- Initialize these values in case the build is not being called form the main Mirth Connect build -->
	<property name="dist" value="dist" />
	<property name="web" value="WebContent" />
	<property name="webadmin" value="../webadmin" />

	<condition property="npmExecutable" value="npm.cmd" else="npm">
        <os family="windows"/>
    </condition>

	<target name="init" depends="clean">
		<mkdir dir="dist" />
	</target>

	<target name="compile">
		<!-- Run npm build on spa -->
		<exec dir="${webadmin}/spa" executable="${npmExecutable}">
			<arg value="install" />
		</exec>
		<exec dir="${webadmin}/spa" executable="${npmExecutable}">
			<arg value="run" />
			<arg value="build" />
		</exec>
	</target>

	<target name="dist" depends="compile">
		<war destfile="dist/webadmin.war" webxml="${webadmin}/${web}/WEB-INF/web.xml">
			<fileset dir="${webadmin}/spa/dist" includes="**" />
		</war>
	</target>

	<target name="clean">
		<delete dir="dist" />
		<delete dir="${webadmin}/spa/dist" />
	</target>
</project>