<?xml version="1.0"?>
<project name="doc-connector" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.doc-connector}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="classes" value="${basedir}/classes" />
	<property name="src" value="${basedir}/src" />
	<property name="lib" value="${basedir}/lib" />
	<property name="dist" value="${server.extensions}/doc" />

	<path id="classpath">
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<fileset dir="${lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="compile">
		<mkdir dir="${classes}" />
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/destination.xml" />
		<copy todir="${dist}/lib" failonerror="false" quiet="true">
			<fileset dir="${lib}" />
		</copy>
		<jar destfile="${dist}/doc-shared.jar" basedir="${classes}">
			<include name="com/mirth/connect/connectors/doc/DocumentDispatcherProperties.class" />
			<include name="com/mirth/connect/connectors/doc/DocumentConnectorServletInterface.class" />
			<include name="com/mirth/connect/connectors/doc/PageSize.class" />
			<include name="com/mirth/connect/connectors/doc/Unit.class" />
		</jar>
		<jar destfile="${dist}/doc-server.jar" basedir="${classes}">
			<exclude name="com/mirth/connect/connectors/doc/DocumentDispatcherProperties.class" />
			<exclude name="com/mirth/connect/connectors/doc/DocumentConnectorServletInterface.class" />
			<exclude name="com/mirth/connect/connectors/doc/PageSize.class" />
			<exclude name="com/mirth/connect/connectors/doc/Unit.class" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/doc-${version}.zip" basedir="${server.extensions}" includes="doc/" />
	</target>

</project>
