<?xml version="1.0"?>
<project name="pdfviewer" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.pdfviewer}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="lib" value="${basedir}/lib" />
	<property name="dist" value="${server.extensions}/pdfviewer" />

	<target name="clean">
	</target>

	<target name="init">
	</target>

	<target name="build" depends="init">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<copy todir="${dist}/lib" quiet="true">
			<fileset dir="${lib}" />
		</copy>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/pdfviewer-${version}.zip" basedir="${server.extensions}" includes="pdfviewer/**/*" />
	</target>

</project>
