<?xml version="1.0"?>
<project name="pdfviewer" basedir="." default="build">

	<dirname property="plugin.dir" file="${ant.file.pdfviewer}"/>
	<property file="${plugin.dir}/../build.properties" />

	<property name="src" value="${basedir}/src" />
	<property name="classes" value="${basedir}/classes" />
	<property name="lib" value="${basedir}/lib" />
	<property name="dist" value="${server.extensions}/pdfviewer" />

	<path id="classpath">
		<fileset dir="${lib}" includes="**/*.jar" />
		<fileset dir="${client.lib}" includes="**/*.jar" />
		<fileset dir="${server.lib}" includes="**/*.jar" />
		<pathelement location="${server.classes}" />
		<pathelement location="${client.classes}" />
	</path>

	<target name="clean">
		<delete dir="${classes}" />
	</target>

	<target name="init">
		<mkdir dir="${classes}" />
	</target>

	<target name="compile" depends="init">
		<javac srcdir="${src}" destdir="${classes}" debug="on" includeAntRuntime="false">
			<classpath refid="classpath" />
		</javac>
	</target>

	<target name="build" depends="compile">
		<mkdir dir="${dist}" />
		<copy todir="${dist}" file="${src}/plugin.xml" />
		<copy todir="${dist}/lib" quiet="true">
			<fileset dir="${lib}" />
		</copy>
		<jar destfile="${dist}/pdfviewer-client.jar" basedir="${classes}">
			<include name="com/mirth/connect/plugins/pdfviewer/**" />
		</jar>
	</target>

	<target name="create-zip">
		<zip destfile="${server.dist.extensions}/pdfviewer-${version}.zip" basedir="${server.extensions}" includes="pdfviewer/**/*" />
	</target>

</project>
